app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

#Route::get('home', 'HomeController@index');
Route::controller('home', 'HomeController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController'
]);


Route::get('authenticateapi', 'Auth\AuthenticateAPIController@authenticate');

Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);



Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Entrust::routeNeedsPermission('users', 'view-user', Redirect::to('/home') );
Entrust::routeNeedsPermission('users/*/edit', 'edit-user', Redirect::to('/home') );
Entrust::routeNeedsPermission('users/create', 'create-user', Redirect::to('/home') );
Route::resource('users', 'UserController');

Route::get('users/{id}/delete', [
    'as' => 'users.delete',
    'uses' => 'UserController@destroy',
]);


Route::resource('users', 'UserController');

Route::get('users/{id}/delete', [
    'as' => 'users.delete',
    'uses' => 'UserController@destroy',
]);


Route::resource('patients', 'PatientController');

// only users with roles that have the view-patient permission can view patients
Entrust::routeNeedsPermission('patients', 'view-patient', Redirect::to('/home'));
// only users with roles that have the 'create-patient' permission will be able to access the patient creation methods
Entrust::routeNeedsPermission('patients/create', 'create-patient', Redirect::to('/home'));

Route::get('patients/{id}/delete', [
    'as' => 'patients.delete',
    'uses' => 'PatientController@destroy',
]);


Route::get('patients/{id}/restore', [
    'as' => 'patients.restore',
    'uses' => 'PatientController@restore',
]);



Route::resource('patientAddresses', 'PatientAddressController');


Route::get('patientAddresses/create/{id}', [
    'as' => 'patientAddresses.create',
    'uses' => 'PatientAddressController@create'
    ]);


Route::get('patientAddresses/{id}/delete', [
    'as' => 'patientAddresses.delete',
    'uses' => 'PatientAddressController@destroy',
]);


Route::resource('patientPhones', 'PatientPhonesController');

Route::get('patientPhones/{id}/delete', [
    'as' => 'patientPhones.delete',
    'uses' => 'PatientPhonesController@destroy',
]);


Route::resource('organizationPatients', 'OrganizationPatientsController');

Route::get('organizationPatients/{id}/delete', [
    'as' => 'organizationPatients.delete',
    'uses' => 'OrganizationPatientsController@destroy',
]);


Route::resource('patientEpisodes', 'PatientEpisodeController');
Route::get('patientEpisodes/create/{id}', [
    'as' => 'patientEpisodes.create',
    'uses' => 'PatientEpisodeController@create'
    ]);
Route::get('patientEpisodes/{id}/delete', [
    'as' => 'patientEpisodes.delete',
    'uses' => 'PatientEpisodeController@destroy',
]);

Route::get('patientEpisodes/getEpisodesByPatientId/{id}', ['as' => 'patientEpisodes.getEpisodesByPatientId', 'uses' => 'PatientEpisodeController@getEpisodesByPatientId']);

Entrust::routeNeedsRole('patientBillCpts*', array('admin','provider'), Redirect::to('/home'), false);
Route::resource('patientBillCpts', 'PatientBillCptController');

Route::get('patientBillCpts/{id}/delete', [
    'as' => 'patientBillCpts.delete',
    'uses' => 'PatientBillCptController@destroy',
]);

Entrust::routeNeedsRole('patientBillIcds*', array('admin','provider'), Redirect::to('/home'), false);

Route::resource('patientBillIcds', 'PatientBillIcdController');

Route::get('patientBillIcds/{id}/delete', [
    'as' => 'patientBillIcds.delete',
    'uses' => 'PatientBillIcdController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('icds', 'IcdController');

Route::get('icds/{id}/delete', [
    'as' => 'icds.delete',
    'uses' => 'IcdController@destroy',
]);

Entrust::routeNeedsRole('patientBills*',array('admin','provider'), Redirect::to('/home'), false);
Route::resource('patientBills', 'PatientBillController');
Route::get('patientBills/{id}/delete', [
    'as' => 'patientBills.delete',
    'uses' => 'PatientBillController@destroy',
]);

Route::get('patientBills/create/{id}', [
    'as' => 'patientBills.create',
    'uses' => 'PatientBillController@create',
]);


Route::resource('roleUsers', 'RoleUserController');

Route::get('roleUsers/{id}/delete', [
    'as' => 'roleUsers.delete',
    'uses' => 'RoleUserController@destroy',
]);


Route::resource('telehealth','TelehealthController');
Entrust::routeNeedsRole('telehealth', array('admin','provider'), Redirect::to('/home'), false);

Route::get('telehealth/connect/{id}', ['as' => 'telehealth.connect', 'uses' => 'TelehealthController@connect'] );

Route::resource('telehealthInvitations', 'TelehealthInvitationController');
Entrust::routeNeedsRole('telehealthInvitations/*', array('admin','provider'), Redirect::to('/home'), false );

Route::get('telehealthInvitations/{id}/delete', [
    'as' => 'telehealthInvitations.delete',
    'uses' => 'TelehealthInvitationController@destroy',
]);


Route::resource('telehealthInvitations', 'TelehealthInvitationController');

Route::get('telehealthInvitations/{id}/delete', [
    'as' => 'telehealthInvitations.delete',
    'uses' => 'TelehealthInvitationController@destroy',
]);


Route::resource('roles', 'RoleController');
Entrust::routeNeedsRole('roles*', 'super_admin', Redirect::to('/home') );
Route::get('roles/{id}/delete', [
    'as' => 'roles.delete',
    'uses' => 'RoleController@destroy',
]);


Route::resource('permissions', 'PermissionController');
Entrust::routeNeedsRole('permissions*', 'super_admin', Redirect::to('/home') );

Route::get('permissions/{id}/delete', [
    'as' => 'permissions.delete',
    'uses' => 'PermissionController@destroy',
]);


Route::resource('permissionRoles', 'PermissionRoleController');
Entrust::routeNeedsRole('permissionRoles*', 'super_admin', Redirect::to('/home') );

Route::get('permissionRoles/{id}/delete', [
    'as' => 'permissionRoles.delete',
    'uses' => 'PermissionRoleController@destroy',
]);


Route::get('icd', 'IcdController@search');
Route::get('cpt', 'CptController@search');



Route::group(['middleware' => 'jwt.auth'], function () {
    Route::resource('api/patients', 'API\PatientAPIController');
    Route::resource('api/users', 'API\UserAPIController');
});

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SGPS</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">
	<link href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

<link href="/vendor/confer/css/confer.css" rel="stylesheet">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
@include('confer::confer')
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="//js.pusher.com/3.0/pusher.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>
@include('confer::js')
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">SGPS</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Home</a></li>
					@if (!Auth::guest())
						@if(Entrust::can('view-user') )
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users<span class="caret"></span></a>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="{{ url('/users/') }}">List</a>
									</li>
							@if(Entrust::can('create-user') )
								<li><a href="{{ url('/users/create') }}">New</a></li>
							@endif
								</ul>
								</li>

						@endif
						@if (Entrust::can('view-patient'))
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Patients<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="{!! route('patients.index') !!}">List</a>
									<a href="{!! route('patients.create') !!}">New</a>
								</li>
							</ul>
						</li>


							@if ( Entrust::can('view-telehealth-session') ) 
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Telehealth<span class="caret"></span></a>
									<ul class="dropdown-menu" role="menu">
										<li>
											<a href="{!! route('telehealth.index') !!}">List Upcoming Sessions</a>
											<a href="{!! route('telehealthInvitations.create') !!}">Schedule New Session</a>
										</li>
									</ul>
								</li>
							@endif
						@endif
					@endif
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }}<span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="/home/">{{ Auth::user()->currentOrganization->name }}</a>
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')
	<!-- Scripts -->
	@yield('scripts');

</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>	
					@if (count($errors) > 0)
					    <div class="alert alert-danger">
					        <ul>
					            @foreach ($errors->all() as $error)
					                <li>{{ $error }}</li>
					            @endforeach
					        </ul>
					    </div>
					@endif
					@if(Session::has('success'))
					    <div class="alert alert-success">
					        <h2>{{ Session::get('success') }}</h2>
					    </div>
					@endif
				<div class="panel-body">
					You are logged in! <br/>
					@if ( count($organizations) > 1 )
					<form action="/home/index"  method="post">
						Choose Organization: 
						{!! Form::select('organization', $organizations, $user->current_org_id); !!}
						<input type="hidden" name="_token" value="{{{ csrf_token() }}}" />
						<input type="submit" value="Choose" />
					</form>
					@endif
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/trash.blade.php
{!! dd($trash) !!}