app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

#Route::get('home', 'HomeController@index');
Route::controller('home', 'HomeController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController'
]);


Route::get('authenticateapi', 'Auth\AuthenticateAPIController@authenticate');

Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);



Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Route::resource('api/organizations', 'API\OrganizationAPIController');

Route::resource('organizations', 'OrganizationController');

Route::get('organizations/{id}/delete', [
    'as' => 'organizations.delete',
    'uses' => 'OrganizationController@destroy',
]);


Entrust::routeNeedsPermission('users', 'view-user', Redirect::to('/home') );
Entrust::routeNeedsPermission('users/*/edit', 'edit-user', Redirect::to('/home') );
Entrust::routeNeedsPermission('users/create', 'create-user', Redirect::to('/home') );
Route::resource('users', 'UserController');

Route::get('users/{id}/delete', [
    'as' => 'users.delete',
    'uses' => 'UserController@destroy',
]);


Route::resource('users', 'UserController');

Route::get('users/{id}/delete', [
    'as' => 'users.delete',
    'uses' => 'UserController@destroy',
]);


Route::resource('patients', 'PatientController');

// only users with roles that have the view-patient permission can view patients
Entrust::routeNeedsPermission('patients', 'view-patient', Redirect::to('/home'));
// only users with roles that have the 'create-patient' permission will be able to access the patient creation methods
Entrust::routeNeedsPermission('patients/create', 'create-patient', Redirect::to('/home'));

Route::get('patients/{id}/delete', [
    'as' => 'patients.delete',
    'uses' => 'PatientController@destroy',
]);


Route::get('patients/{id}/restore', [
    'as' => 'patients.restore',
    'uses' => 'PatientController@restore',
]);



Route::resource('patientAddresses', 'PatientAddressController');


Route::get('patientAddresses/create/{id}', [
    'as' => 'patientAddresses.create',
    'uses' => 'PatientAddressController@create'
    ]);


Route::get('patientAddresses/{id}/delete', [
    'as' => 'patientAddresses.delete',
    'uses' => 'PatientAddressController@destroy',
]);


Route::resource('patientPhones', 'PatientPhonesController');

Route::get('patientPhones/{id}/delete', [
    'as' => 'patientPhones.delete',
    'uses' => 'PatientPhonesController@destroy',
]);


Route::resource('organizationPatients', 'OrganizationPatientsController');

Route::get('organizationPatients/{id}/delete', [
    'as' => 'organizationPatients.delete',
    'uses' => 'OrganizationPatientsController@destroy',
]);


Route::resource('patientEpisodes', 'PatientEpisodeController');
Route::get('patientEpisodes/create/{id}', [
    'as' => 'patientEpisodes.create',
    'uses' => 'PatientEpisodeController@create'
    ]);
Route::get('patientEpisodes/{id}/delete', [
    'as' => 'patientEpisodes.delete',
    'uses' => 'PatientEpisodeController@destroy',
]);

Route::get('patientEpisodes/getEpisodesByPatientId/{id}', ['as' => 'patientEpisodes.getEpisodesByPatientId', 'uses' => 'PatientEpisodeController@getEpisodesByPatientId']);

Entrust::routeNeedsRole('patientBillCpts*', array('admin','provider'), Redirect::to('/home'), false);
Route::resource('patientBillCpts', 'PatientBillCptController');

Route::get('patientBillCpts/{id}/delete', [
    'as' => 'patientBillCpts.delete',
    'uses' => 'PatientBillCptController@destroy',
]);

Entrust::routeNeedsRole('patientBillIcds*', array('admin','provider'), Redirect::to('/home'), false);

Route::resource('patientBillIcds', 'PatientBillIcdController');

Route::get('patientBillIcds/{id}/delete', [
    'as' => 'patientBillIcds.delete',
    'uses' => 'PatientBillIcdController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('cpts', 'CptController');

Route::get('cpts/{id}/delete', [
    'as' => 'cpts.delete',
    'uses' => 'CptController@destroy',
]);


Route::resource('icds', 'IcdController');

Route::get('icds/{id}/delete', [
    'as' => 'icds.delete',
    'uses' => 'IcdController@destroy',
]);

Entrust::routeNeedsRole('patientBills*',array('admin','provider'), Redirect::to('/home'), false);
Route::resource('patientBills', 'PatientBillController');
Route::get('patientBills/{id}/delete', [
    'as' => 'patientBills.delete',
    'uses' => 'PatientBillController@destroy',
]);

Route::get('patientBills/create/{id}', [
    'as' => 'patientBills.create',
    'uses' => 'PatientBillController@create',
]);


Route::resource('roleUsers', 'RoleUserController');

Route::get('roleUsers/{id}/delete', [
    'as' => 'roleUsers.delete',
    'uses' => 'RoleUserController@destroy',
]);


Route::resource('telehealth','TelehealthController');
Entrust::routeNeedsRole('telehealth', array('admin','provider'), Redirect::to('/home'), false);

Route::get('telehealth/connect/{id}', ['as' => 'telehealth.connect', 'uses' => 'TelehealthController@connect'] );

Route::resource('telehealthInvitations', 'TelehealthInvitationController');
Entrust::routeNeedsRole('telehealthInvitations/*', array('admin','provider'), Redirect::to('/home'), false );

Route::get('telehealthInvitations/{id}/delete', [
    'as' => 'telehealthInvitations.delete',
    'uses' => 'TelehealthInvitationController@destroy',
]);


Route::resource('telehealthInvitations', 'TelehealthInvitationController');

Route::get('telehealthInvitations/{id}/delete', [
    'as' => 'telehealthInvitations.delete',
    'uses' => 'TelehealthInvitationController@destroy',
]);


Route::resource('roles', 'RoleController');
Entrust::routeNeedsRole('roles*', 'super_admin', Redirect::to('/home') );
Route::get('roles/{id}/delete', [
    'as' => 'roles.delete',
    'uses' => 'RoleController@destroy',
]);


Route::resource('permissions', 'PermissionController');
Entrust::routeNeedsRole('permissions*', 'super_admin', Redirect::to('/home') );

Route::get('permissions/{id}/delete', [
    'as' => 'permissions.delete',
    'uses' => 'PermissionController@destroy',
]);


Route::resource('permissionRoles', 'PermissionRoleController');
Entrust::routeNeedsRole('permissionRoles*', 'super_admin', Redirect::to('/home') );

Route::get('permissionRoles/{id}/delete', [
    'as' => 'permissionRoles.delete',
    'uses' => 'PermissionRoleController@destroy',
]);


Route::get('icd', 'IcdController@search');
Route::get('cpt', 'CptController@search');



Route::group(['middleware' => 'jwt.auth'], function () {
    Route::resource('api/patients', 'API\PatientAPIController');
    Route::resource('api/users', 'API\UserAPIController');
});

app/Models/PatientEpisode.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PatientEpisode extends Model
{
    
	public $table = "patient_episodes";

	public $primaryKey = "id";
    
	public $timestamps = true;

	public $fillable = [
	    "patient_id",
                "episode_date",
	];

	public static $rules = [
	    "patient_id" => "required",
                "episode_date" => "required",
	];

            public function bills()
            {
                return $this->hasMany('App\Models\PatientBill');
            }

            public function patient()
            {
                return $this->belongsTo('App\Models\Patient');
            }
}

app/Http/Controllers/PatientEpisodeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreatePatientEpisodeRequest;
use Illuminate\Http\Request;
use App\Libraries\Repositories\PatientEpisodeRepository;
use Mitul\Controller\AppBaseController;
use Response;
use Flash;

class PatientEpisodeController extends AppBaseController
{

	/** @var  PatientEpisodeRepository */
	private $patientEpisodeRepository;

	function __construct(PatientEpisodeRepository $patientEpisodeRepo)
	{
		$this->patientEpisodeRepository = $patientEpisodeRepo;
	}

	/**
	 * Display a listing of the PatientEpisode.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
	    $input = $request->all();

		$result = $this->patientEpisodeRepository->search($input);

		$patientEpisodes = $result[0];

		$attributes = $result[1];

		return view('patientEpisodes.index')
		    ->with('patientEpisodes', $patientEpisodes)
		    ->with('attributes', $attributes);;
	}

	/**
	 * Show the form for creating a new PatientEpisode.
	 *
	 * @return Response
	 */
	public function create($patient_id)
	{
		$patientEpisode = new \App\Models\PatientEpisode();
		$patientEpisode->patient_id = $patient_id;

		$patient = \App\Models\Patient::find($patient_id);

		return view('patientEpisodes.create')->with('patientEpisode', $patientEpisode)->with('patient', $patient);
	}

	/**
	 * Store a newly created PatientEpisode in storage.
	 *
	 * @param CreatePatientEpisodeRequest $request
	 *
	 * @return Response
	 */
	public function store(CreatePatientEpisodeRequest $request)
	{
        $input = $request->all();

		$patientEpisode = $this->patientEpisodeRepository->store($input);

		Flash::message('PatientEpisode saved successfully.');

		return redirect(route('patientEpisodes.index'));
	}

	/**
	 * Display the specified PatientEpisode.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$patientEpisode = $this->patientEpisodeRepository->findPatientEpisodeById($id);

		if(empty($patientEpisode))
		{
			Flash::error('PatientEpisode not found');
			return redirect(route('patientEpisodes.index'));
		}

		return view('patientEpisodes.show')->with('patientEpisode', $patientEpisode);
	}

	/**
	 * Show the form for editing the specified PatientEpisode.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$patientEpisode = $this->patientEpisodeRepository->findPatientEpisodeById($id);

		if(empty($patientEpisode))
		{
			Flash::error('PatientEpisode not found');
			return redirect(route('patientEpisodes.index'));
		}
		$patient = \App\Models\Patient::find($patientEpisode->patient_id);
		return view('patientEpisodes.edit')->with('patientEpisode', $patientEpisode)->with('patient',$patient);
	}

	/**
	 * Update the specified PatientEpisode in storage.
	 *
	 * @param  int    $id
	 * @param CreatePatientEpisodeRequest $request
	 *
	 * @return Response
	 */
	public function update($id, CreatePatientEpisodeRequest $request)
	{
		$patientEpisode = $this->patientEpisodeRepository->findPatientEpisodeById($id);

		if(empty($patientEpisode))
		{
			Flash::error('PatientEpisode not found');
			return redirect(route('patientEpisodes.index'));
		}

		$patientEpisode = $this->patientEpisodeRepository->update($patientEpisode, $request->all());

		Flash::message('PatientEpisode updated successfully.');

		return redirect(route('patientEpisodes.index'));
	}

	/**
	 * Remove the specified PatientEpisode from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		$patientEpisode = $this->patientEpisodeRepository->findPatientEpisodeById($id);

		if(empty($patientEpisode))
		{
			Flash::error('PatientEpisode not found');
			return redirect(route('patientEpisodes.index'));
		}

		$patientEpisode->delete();

		Flash::message('PatientEpisode deleted successfully.');

		return redirect(route('patientEpisodes.index'));
	}


	public function getEpisodesByPatientId($id)
	{
		$patientEpisode = \App\Models\PatientEpisode::where('patient_id', $id)->get();
		return $patientEpisode;
	}
}

resources/views/patientEpisodes/create.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($patientEpisode, ['route' => 'patientEpisodes.store']) !!}

        @include('patientEpisodes.fields')

    {!! Form::close() !!}
</div>
@endsection

@section('scripts')
<script>
$(document).ready( function() {
        $( "#episode_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
      dateFormat: "yy-mm-dd"
    });

});
</script>
@endsection

resources/views/patientEpisodes/edit.blade.php
@extends('app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($patientEpisode, ['route' => ['patientEpisodes.update', $patientEpisode->id], 'method' => 'patch']) !!}

        @include('patientEpisodes.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/patientEpisodes/fields.blade.php
<!--- Patient Id Field --->
<!-- <div class="form-group col-sm-6 col-lg-4"> 
    {!! Form::label('patient_id', 'Patient Id:') !!} -->
    {!! Form::hidden('patient_id', null, ['class' => 'form-control', 'readonly']) !!}
<!-- </div> -->

<div class="form-group col-sm-12">
    {!! $patient->firstName !!} {!! $patient->middleName !!} {!! $patient->lastName !!} {!! $patient->birthDate !!}
</div>

<div class="form-group col-sm-12">
    {!! Form::label('episode_date','Episode Date') !!}
    {!! Form::text('episode_date', null, ['class' => 'form-control']) !!}
</div>

<!--- Submit Field --->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/patientEpisodes/index.blade.php
@extends('app')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">PatientEpisodes</h1>
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('patientEpisodes.create') !!}">Add New</a>
        </div>

        <div class="row">
            @if($patientEpisodes->isEmpty())
                <div class="well text-center">No PatientEpisodes found.</div>
            @else
                <table class="table">
                    <thead>
                    <th>Patient</th>
                    <th>Episode Date</th>
                    <th>Bills</th>
                    <th width="50px">Action</th>
                    </thead>
                    <tbody>
                     
                    @foreach($patientEpisodes as $patientEpisode)
                        <tr>
                            <td>{!! $patientEpisode->patient->firstName !!} {!! $patientEpisode->patient->middleName !!} {!! $patientEpisode->patient->lastName !!}</td>
                            <td>{!! $patientEpisode->episode_date !!}</td>
                            <td>
                                <a href="{!! route('patientBills.create', $patientEpisode->id) !!}" class="btn btn-xs btn-primary">Add New Bill</a>
                                <br/>
                                @foreach($patientEpisode->bills as $bill)
                                    {!! $bill->created_at !!} <a href="{!! route('patientBills.edit', $bill->id) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                                @endforeach
                            </td>
                            <td>
                                <a href="{!! route('patientEpisodes.edit', [$patientEpisode->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                                <a href="{!! route('patientEpisodes.delete', [$patientEpisode->id]) !!}" onclick="return confirm('Are you sure wants to delete this PatientEpisode?')"><i class="glyphicon glyphicon-remove"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>
@endsection

resources/views/patientEpisodes/show.blade.php
@extends('app')

@section('content')
<div class="container">
</div>
@endsection